# Generated by Django 3.2.7 on 2021-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_job_seeker_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
