# Generated by Django 3.2.7 on 2021-11-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_seeker_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
