# Generated by Django 3.2.7 on 2021-11-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
