# Generated by Django 3.2.7 on 2021-11-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_recruiter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='status',
        ),
    ]
