# Generated by Django 3.2.7 on 2021-11-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='recruiter',
            new_name='recruiter1',
        ),
    ]
