# Generated by Django 3.2.7 on 2022-01-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='experience',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='experience_cmp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
