# Generated by Django 3.2.7 on 2022-01-19 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('recruiter1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.recruiter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job_seeker')),
            ],
        ),
        migrations.DeleteModel(
            name='quiz',
        ),
    ]
