# Generated by Django 3.2.7 on 2022-01-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20220119_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='student',
        ),
    ]
