# Generated by Django 3.2.7 on 2022-01-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_remove_rating_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job_seeker'),
        ),
    ]
