from django.urls import path
from job import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('',views.home, name='home'),
    path('contact/',views.contact,name="contact"),
    path('about/',views.about,name='about'),
    path('user_login/',views.user_login,name='user_login'),
    path('recruiter_login/',views.recruiter_login,name='recruiter_login'),
    path('signup_jobseeker/',views.signup_jobseeker,name='signup_jobseeker'),
    path('signup_recruiter/',views.signup_recruiter,name='signup_recruiter'),
    path('recruiter_home/',views.recruiter_home,name='recruiter_home'),
    path('user_home/',views.user_home,name='user_home'),
    path('user_about/',views.user_about,name='user_about'),
    path('user_contact/',views.user_contact,name='user_contact'),
    path('recruiter_about/',views.recruiter_about,name='recruiter_about'),
    path('recruiter_contact/',views.recruiter_contact,name='recruiter_contact'),
    path('Logout/',views.Logout,name='Logout'),
    path('post_job/',views.add_job,name='add_job'),
    path('job_list/',views.job_list,name='job_list'),
    path('edit_jobdetail/<int:pid>',views.edit_jobdetail,name='edit_jobdetail'),
    path('alljobs/',views.alljobs,name='alljobs'),
    path('alljobs_base/',views.alljobs_base,name='alljobs_base'),
    path('job_detail/<int:uid>',views.job_detail,name='job_detail'),
    path('apply_job/<int:uid>',views.apply_job,name='apply_job'),
    path('delete_job/<int:pid>',views.delete_job,name='delete_job'),
    path('candidates_applied',views.candidates_applied,name='candidates_applied'),
    path('user_home/search_jobs/',views.search_jobs,name='search_jobs'),
    path('search/',views.search,name='search'),
    path('job_detail_home/<int:uid>',views.job_detail,name='job_detail_home '),
    path('recruiter_home/quiz_form',views.quiz_form,name="quiz_form"),
    path('notification/',views.notification,name='notification'),
    path('user_detail/<int:uid>',views.user_detail,name='user_detail'),
    path('rate/', views.rate_image, name='rate-view'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)